changed(chezmoi): replace '.chezmoi.os' with $C_OS

diff --git a/run_onchange_install_packages.bash.tmpl b/run_onchange_install_packages.bash.tmpl
--- a/run_onchange_install_packages.bash.tmpl
+++ b/run_onchange_install_packages.bash.tmpl
@@ -9,13 +9,14 @@
 ####[ Global Variables ]####################################################################
 
 
+C_OS="$(uname -s)"
 C_YELLOW="$(printf '\033[1;33m')"
 C_GREEN="$(printf '\033[0;32m')"
 C_BLUE="$(printf '\033[0;34m')"
 C_CYAN="$(printf '\033[0;36m')"
 C_RED="$(printf '\033[1;31m')"
 C_NC="$(printf '\033[0m')"
-readonly C_YELLOW C_GREEN C_BLUE C_RED C_CYAN C_NC
+readonly C_OS C_YELLOW C_GREEN C_BLUE C_RED C_CYAN C_NC
 
 readonly C_WARNING="${C_YELLOW}==>${C_NC} "
 readonly C_SUCCESS="${C_GREEN}==>${C_NC} "
@@ -64,7 +65,7 @@ install_from_cache() {
 
 echo "${C_INFO}Starting package installation process..."
 
-if [[ $EUID -ne 0 && $(uname -s) != Darwin ]]; then
+if [[ $EUID -ne 0 && $C_OS != "Darwin" ]]; then
     echo "${C_NOTE}This step requires administrative rights"
     read -rp "${C_NOTE}Do you want to continue? [y/N]: " answer
 
@@ -76,7 +77,7 @@ if [[ $EUID -ne 0 && $(uname -s) != Darwin ]]; then
 fi
 
 # shellcheck disable=SC1009,SC1054,SC1056,SC1072,SC1073,SC1083
-case "{{ .chezmoi.os }}" in
+case "$C_OS" in
     linux)
         if command -v pacman >/dev/null; then
             echo "${C_INFO}Updating package lists..."
@@ -129,7 +130,7 @@ case "{{ .chezmoi.os }}" in
         ;;
 
     *)
-        echo "${C_ERROR}Unsupported operating system: {{ .chezmoi.os }}" >&2
+        echo "${C_ERROR}Unsupported operating system: $C_OS" >&2
         echo "${C_NOTE}Skipping package installation"
         echo ""
         exit 1
