added(chezmoi): implement minimum requirement checks

diff --git a/run_before_01_precompute.bash.tmpl b/run_before_01_precompute.bash.tmpl
--- a/run_before_01_precompute.bash.tmpl
+++ b/run_before_01_precompute.bash.tmpl
@@ -13,15 +13,18 @@ readonly C_OS
 C_YELLOW="$(printf '\033[1;33m')"
 C_GREEN="$(printf '\033[0;32m')"
 C_BLUE="$(printf '\033[0;34m')"
+C_CYAN="$(printf '\033[0;36m')"
 C_NC="$(printf '\033[0m')"
 readonly C_YELLOW C_GREEN C_BLUE C_NC
 
 readonly C_WARNING="${C_YELLOW}==>${C_NC} "
 readonly C_SUCCESS="${C_GREEN}==>${C_NC} "
 readonly C_INFO="${C_BLUE}==>${C_NC} "
+readonly C_NOTE="${C_CYAN}==>${C_NC} "
 
 # shellcheck disable=all
 C_CHEZMOI_DIR={{ .chezmoi.sourceDir | quote }}
+readonly C_CHEZMOI_DIR
 # shellcheck enable=all
 
 
@@ -31,14 +34,32 @@ C_CHEZMOI_DIR={{ .chezmoi.sourceDir | quote }}
 echo "${C_INFO}Running precompute script..."
 
 ###
+### [ Minimum Requirements Check ]
+###
+
+echo "${C_INFO}  Checking minimum requirements are met..."
+
+if [[ $C_OS != "Darwin" && $C_OS != "Linux" ]]; then
+    echo "${C_ERROR}Unsupported operating system: $C_OS" >&2
+    echo "${C_NOTE}These Chezmoi scripts only support macOS and Linux"
+    exit 1
+fi
+
+if [[ $C_OS == "Darwin" ]] && ! command -v brew &>/dev/null; then
+    echo "${C_ERROR}Homebrew is not installed" >&2
+    echo "${C_NOTE}Please install Homebrew first"
+    exit 1
+fi
+
+###
 ### [ Tool Presence Checks ]
 ###
 
 echo "${C_INFO}  Checking if 'git-delta' is installed..."
 if command -v delta >/dev/null; then
-    C_IS_DELTA_INSTALLED=true
+    is_delta_installed=true
 else
-    C_IS_DELTA_INSTALLED=false
+    is_delta_installed=false
 fi
 
 ###
@@ -49,9 +70,9 @@ echo "${C_INFO}  Checking if GUI environment is present..."
 
 if [[ $C_OS == "Darwin" ]]; then
     if launchctl print "gui/$(id -u)" &>/dev/null; then
-        C_IS_GUI_ENVIRONMENT=true
+        is_gui_environment=true
     else
-        C_IS_GUI_ENVIRONMENT=false
+        is_gui_environment=false
     fi
 elif [[ $C_OS == "Linux" ]]; then
     if pgrep -x gdm >/dev/null \
@@ -61,16 +82,12 @@ elif [[ $C_OS == "Linux" ]]; then
         || pgrep -x wayland >/dev/null \
         || [[ -n $DISPLAY ]] \
         || [[ $XDG_SESSION_TYPE == "wayland" ]] \
-        || [[ $XDG_SESSION_TYPE = "x11" ]]
+        || [[ $XDG_SESSION_TYPE == "x11" ]]
     then
-        C_IS_GUI_ENVIRONMENT=true
+        is_gui_environment=true
     else
-        C_IS_GUI_ENVIRONMENT=false
+        is_gui_environment=false
     fi
-else
-    echo "${C_WARNING}  Unsupported operating system: $C_OS" >&2
-    echo "${C_INFO}  Assuming headless environment"
-    C_IS_GUI_ENVIRONMENT=false
 fi
 
 ###
@@ -80,8 +97,8 @@ fi
 echo "${C_INFO}  Writing precomputed data to file..."
 cat > "${C_CHEZMOI_DIR}/.precomputed_data.json" <<EOF
 {
-    "isDeltaInstalled": $C_IS_DELTA_INSTALLED,
-    "isGUIEnvironment": $C_IS_GUI_ENVIRONMENT
+    "isDeltaInstalled": $is_delta_installed,
+    "isGUIEnvironment": $is_gui_environment
 }
 EOF
 
